version: '3.1'

services:

  db:
    image: postgres
    restart: always
    container_name: graph-model
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: graph
    ports:
      - 5511:5432
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
